--TOPCATEGORY

INSERT INTO TOPCATEGORY (TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_TOPCATEGORY.NEXTVAL, '상의');

INSERT INTO TOPCATEGORY (TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_TOPCATEGORY.NEXTVAL, '하의');

INSERT INTO TOPCATEGORY (TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_TOPCATEGORY.NEXTVAL, '액세서리');

INSERT INTO TOPCATEGORY (TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_TOPCATEGORY.NEXTVAL, '신발');



--SUBCATEGORY

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 1, '셔츠');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 1, '니트');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 1, '코트');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 1, '점퍼');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 2, '청바지');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 2, '면바지');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 2, '반바지');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 2, '치마');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 3, '시계');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 3, '팔찌');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 3, '귀걸이');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 3, '지갑');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 4, '운동화');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 4, '구두');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 4, '샌들');

INSERT INTO SUBCATEGORY (SUBCATEGORY_ID, TOPCATEGORY_ID, TITLE)
     VALUES (SEQ_SUBCATEGORY.NEXTVAL, 4, '슬리퍼');



-- PROMOTION

INSERT INTO PROMOTION (PROMOTION_ID, TITLE)
     VALUES (SEQ_PROMOTION.NEXTVAL, '신상품');

INSERT INTO PROMOTION (PROMOTION_ID, TITLE)
     VALUES (SEQ_PROMOTION.NEXTVAL, '계절상품');

INSERT INTO PROMOTION (PROMOTION_ID, TITLE)
     VALUES (SEQ_PROMOTION.NEXTVAL, 'MD추천상품');

INSERT INTO PROMOTION (PROMOTION_ID, TITLE)
     VALUES (SEQ_PROMOTION.NEXTVAL, '인기상품');