CREATE TABLESPACE SHOPPING
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\SHOPPING.DBF'
SIZE 2M;

CREATE USER shop
IDENTIFIED BY shop
DEFAULT TABLESPACE SHOPPING
QUOTA UNLIMITED ON SHOPPING;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO shop;

CREATE TABLE PROMOTION
(
   PROMOTION_ID   NUMBER PRIMARY KEY,
   TITLE          VARCHAR2 (30)
);

CREATE TABLE TOPCATEGORY
(
   TOPCATEGORY_ID   NUMBER PRIMARY KEY,
   TITLE            VARCHAR2 (20)
);

CREATE TABLE SUBCATEGORY
(
   SUBCATEGORY_ID   NUMBER PRIMARY KEY,
   TOPCATEGORY_ID   NUMBER,
   TITLE            VARCHAR2 (30)
);

CREATE TABLE PRODUCT
(
   PRODUCT_ID       NUMBER PRIMARY KEY,
   SUBCATEGORY_ID   NUMBER,
   PRODUCT_NAME     VARCHAR2 (30),
   PRICE            NUMBER DEFAULT 0,
   STOCK            NUMBER DEFAULT 0,
   IMG              VARCHAR2 (20),
   DETAIL           CLOB
);

CREATE TABLE PROMOTION_PRODUCT
(
   PROMOTION_PRODUCT_ID   NUMBER PRIMARY KEY,
   PRODUCT_ID             NUMBER,
   PROMOTION_ID           NUMBER
);



CREATE SEQUENCE SEQ_PROMOTION INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SEQ_TOPCATEGORY INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SEQ_SUBCATEGORY INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SEQ_PRODUCT INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE SEQ_PROMOTION_PRODUCT INCREMENT BY 1 START WITH 1;